name: CI/CD Pipeline for Airline Passenger Satisfaction Classification Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: Azure Login using Service Principal
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: "SERVICE_PRINCIPAL"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[all] mlflow joblib pandas flask

      # Step 5: Set up DVC remote
      - name: Configure DVC Remote
        run: |
          dvc remote add -d myremote ./dvc_remote_storage
          dvc remote list

      # Step 6: Set the subscription for deployment
      - name: 'Set Azure Subscription'
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 7: Check if Azure Web App exists and create it if necessary
      - name: 'Create Azure Web App (if not exists)'
        run: |
          az webapp show --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} || \
          az webapp create --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --plan B1 --runtime "PYTHON|3.8"

      # Step 5: Pull data and artifacts
      - name: Pull DVC Artifacts
        run: dvc pull

      # Step 6: Run DVC pipeline stages
      - name: Run DVC Pipeline
        run: dvc repro

      # Step 7: Push results to DVC remote storage
      - name: Push DVC Artifacts
        run: dvc push

      # # Step 8: Deploy Flask App
      # - name: Deploy Flask App
      #   run: |
      #     chmod +x run_flask.sh
      #     ./run_flask.sh

      # Step 9: Deploy to Azure Web App
      - name: 'Deploy Flask app to Azure Web App'
        run: |
          az webapp up --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --plan B1 --sku B1 --location eastus
        
      # Step 10: Notify deployment success
      - name: Notify Deployment Success 
        run: echo "Deployment Successful!"
