name: CI/CD Pipeline for Airline Passenger Satisfaction Classification Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[all] mlflow joblib pandas flask

      # Step 4: Set up DVC remote
      - name: Configure DVC Remote
        run: |
          dvc remote add -d myremote ./dvc_remote_storage
          dvc remote list

      # Step 5: Create a Docker image
      - name: Build Docker Image
      run: |
        docker build -t airline-satisfaction-app .

      # Step 6: Run Flask app in the background
      - name: Start Flask App in Background
        run: |
          docker run -d -p 2000:2000 airline-satisfaction-app

      # Step 11: Notify deployment success
      - name: Notify Deployment Success 
        run: echo "Deployment Successful!"
